run:
  go: "1.24"
  timeout: 5m
  tests: false

linters:
  disable-all: true
  enable:
    - errcheck
    - bodyclose
    - contextcheck
    - copyloopvar
    - durationcheck
    - errname
    - errorlint
    - forcetypeassert
    - godot
    - goprintffuncname
    - intrange
    - makezero
    - misspell
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - wastedassign
    - whitespace
    - govet

linters-settings:
  exhaustive:
    default-signifies-exhaustive: false
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - performance
      - style
    disabled-checks:
      - hugeParam
      - rangeValCopy
      - ifElseChain
      - typeAssertChain
      - unnamedResult
      - importShadow
      - emptyStringTest
      - exitAfterDefer
  govet:
    disable:
      - fieldalignment
    enable-all: true
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
        disabled: true
      - name: var-declaration
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code
      - name: redefines-builtin-id
      - name: package-comments
        disabled: true
      - name: exported
        disabled: true
      - name: unused-parameter
        disabled: true
  gosec:
    excludes:
      - G304
      - G204
      - G115
      - G301
      - G101

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude all from tests
    - path: "_test\\.go"
      linters:
        - errcheck
        - gosec
        - revive
        - gocritic
    - linters:
        - revive
      text: "package-comments:"
    - linters:
        - revive
      text: "exported:"
    - linters:
        - revive
      text: "unused-parameter:"
    - linters:
        - revive
      text: "var-naming:"
    - linters:
        - gosec
      text: "G304:"
    - linters:
        - gosec
      text: "G204:"
    - linters:
        - gosec
      text: "G115:"
    - linters:
        - gosec
      text: "G301:"
    - linters:
        - gosec
      text: "G101:"
    - linters:
        - gocritic
      text: "exitAfterDefer:"
    - linters:
        - gocritic
      text: "ifElseChain:"
    - linters:
        - exhaustive
      text: "missing cases in switch"
    - linters:
        - revive
      text: "stutter"
